export enum FriendErrorCode {
  CANNOT_FRIEND_SELF = 'FRIEND_CANNOT_FRIEND_SELF',
  USER_NOT_FOUND = 'FRIEND_USER_NOT_FOUND',
  ALREADY_FRIENDS = 'FRIEND_ALREADY_FRIENDS',
  REQUEST_ALREADY_PENDING = 'FRIEND_REQUEST_ALREADY_PENDING',
  REQUEST_BLOCKED = 'FRIEND_REQUEST_BLOCKED',
  REQUEST_NOT_FOUND = 'FRIEND_REQUEST_NOT_FOUND',
  FRIENDSHIP_NOT_FOUND = 'FRIENDSHIP_NOT_FOUND',
  AUTHORS_CANNOT_FRIEND = 'FRIEND_AUTHORS_CANNOT_FRIEND',
}
