export enum AuthorFollowErrorCode {
  CANNOT_FOLLOW_SELF = 'AUTHOR_FOLLOW_CANNOT_FOLLOW_SELF',
  AUTHOR_NOT_FOUND = 'AUTHOR_FOLLOW_AUTHOR_NOT_FOUND',
  ALREADY_FOLLOWING = 'AUTHOR_FOLLOW_ALREADY_FOLLOWING',
  NOT_FOLLOWING = 'AUTHOR_FOLLOW_NOT_FOLLOWING',
}
