export enum ReviewErrorCode {
  APPLICATION_NOT_FOUND = 'REVIEW_APPLICATION_NOT_FOUND',
  APPLICATION_NOT_APPROVED = 'REVIEW_APPLICATION_NOT_APPROVED',
  APPLICATION_NOT_RECEIVED = 'REVIEW_APPLICATION_NOT_RECEIVED',
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  REVIEW_NOT_FOUND = 'REVIEW_NOT_FOUND',
  ACCESS_DENIED = 'REVIEW_ACCESS_DENIED',
  AUTHOR_ACCESS_REQUIRED = 'REVIEW_AUTHOR_ACCESS_REQUIRED',
  NOT_AUTHOR_OF_BOOK = 'REVIEW_NOT_AUTHOR_OF_BOOK',
}
