export enum FileErrorCode {
  FILE_REQUIRED = 'FILE_REQUIRED',
  FILE_BUFFER_MISSING = 'FILE_BUFFER_MISSING',
  FILE_ORIGINAL_NAME_MISSING = 'FILE_ORIGINAL_NAME_MISSING',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_ACCESS_DENIED = 'FILE_ACCESS_DENIED',
  FILE_DELETE_FAILED = 'FILE_DELETE_FAILED',
}
