export enum UserErrors {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_EMAIL_NOT_VERIFIED = 'USER_EMAIL_NOT_VERIFIED',
  USER_NOT_ACTIVE = 'USER_NOT_ACTIVE',
  USER_NOT_AUTHOR = 'USER_NOT_AUTHOR',
  USER_NOT_READER = 'USER_NOT_READER',
  USER_ACCESS_DENIED = 'USER_ACCESS_DENIED',
  USER_INVALID_CREDENTIALS = 'USER_INVALID_CREDENTIALS',
  USER_ALREADY_VERIFIED = 'USER_ALREADY_VERIFIED',
}   
